"""GATE-DICTPAGE: the published dictation reference cannot fall behind the code.

``docs/site/dictation.html`` is authored prose with one generated region in it:
everything dictation *listens for* -- the punctuation, bracket, symbol and layout
phrases and the spoken commands -- comes from
:mod:`quill.core.windows_dictation.vocabulary`, which is also what the in-app
"What can I say?" window and both editors' ``dictation-commands`` guides render.

A fourth hand-maintained copy would go stale the first time somebody taught
dictation a new phrase, and nobody would notice, because a missing row looks
exactly like a page that never had it. So the region is generated by
``scripts/build_dictation_page.py`` and this gate fails when it drifts.

It also pins the two things that make those tables readable to the audience the
page is for, because both are easy to lose in an edit and neither is visible as a
defect: every value cell names its character in words as well as showing it, and
every row leads with a ``th scope="row"``.
"""

from __future__ import annotations

import importlib.util
import re
from pathlib import Path

_ROOT = Path(__file__).resolve().parents[3]
_PAGE = _ROOT / "docs" / "site" / "dictation.html"
_BUILDER = _ROOT / "scripts" / "build_dictation_page.py"


def _builder():
    spec = importlib.util.spec_from_file_location("build_dictation_page", _BUILDER)
    assert spec and spec.loader
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def test_the_generated_region_is_current() -> None:
    build = _builder()
    assert build.current().replace("\r\n", "\n") == build.rendered(), (
        "docs/site/dictation.html's vocabulary region is behind "
        "quill/core/windows_dictation/vocabulary.py. Run: "
        "python scripts/build_dictation_page.py"
    )


def test_every_phrase_dictation_knows_is_on_the_page() -> None:
    """The page lists the whole vocabulary, not a subset somebody trimmed."""
    from quill.core.windows_dictation.vocabulary import COMMAND_HELP, MARKS

    page = _PAGE.read_text(encoding="utf-8")
    missing = [
        " ".join(mark.phrase) for mark in MARKS if f">{' '.join(mark.phrase)}</th>" not in page
    ]
    assert not missing, f"marks absent from the published page: {missing}"
    absent = [entry.phrases[0] for entry in COMMAND_HELP if entry.phrases[0] not in page]
    assert not absent, f"spoken commands absent from the published page: {absent}"


def test_no_cell_is_a_bare_symbol() -> None:
    """A cell holding only punctuation reads as nothing.

    NVDA and JAWS announce a lone "." at one punctuation verbosity level and skip
    it at another, so a ``Writes`` column of bare characters would be silent for
    exactly the rows somebody looks up -- the same finding that keeps tick and
    cross glyphs out of the comparison tables. The builder therefore prints the
    character *and* names it, and raises for a character it has no name for.
    """
    page = _PAGE.read_text(encoding="utf-8")
    start = page.index("<!-- dictation-vocabulary:start -->")
    end = page.index("<!-- dictation-vocabulary:end -->")
    region = page[start:end]

    offenders = []
    for cell in re.findall(r"<td>(.*?)</td>", region, re.S):
        words = re.sub(r"<[^>]+>", "", cell)
        # Strip the character the cell shows; what is left must be real words.
        letters = re.sub(r"[^A-Za-z]", "", words)
        if len(letters) < 3:
            offenders.append(cell)
    assert not offenders, (
        "these generated cells carry no words, so a screen reader may read them "
        f"as blank: {offenders[:5]}"
    )


def test_every_generated_row_has_a_row_header() -> None:
    page = _PAGE.read_text(encoding="utf-8")
    start = page.index("<!-- dictation-vocabulary:start -->")
    end = page.index("<!-- dictation-vocabulary:end -->")
    rows = re.findall(r"<tr>(.*?)</tr>", page[start:end], re.S)
    assert rows, "the generated region has no table rows at all"
    bad = [row for row in rows if 'scope="row"' not in row and 'scope="col"' not in row]
    assert not bad, (
        'every row needs a th scope="row" or it reads as "Yes" with nothing to say '
        f"what is being answered: {bad[:3]}"
    )


def test_every_chord_the_page_teaches_is_a_dictation_chord() -> None:
    """A chord in a key cell must belong to a dictation command.

    "Is it bound?" is the wrong question and would have missed the defect this
    gate was written for: an early draft of the page offered Ctrl+Alt+Shift+K as
    a dictation key, and that chord *is* bound -- to the AI Privacy Agreement. A
    reader following the page would have opened the wrong window with nothing
    anywhere to say the page was wrong, which is the worst shape a documentation
    bug comes in.

    Neither existing chord gate can see this page: both read Markdown tuples and
    match backticks or bold, and this is a table cell in the site shell. The
    pairing here is stronger than either of them, because the markup states it
    outright -- th[scope="row"] names the command and td.key holds its chord.
    """
    from quill.core.keymap import DEFAULT_KEYMAP
    from quill.core.lite.keymap import COMMANDS as LITE_COMMANDS

    owners: dict[str, set[str]] = {}
    for command_id, chord in DEFAULT_KEYMAP.items():
        if chord:
            owners.setdefault(chord, set()).add(command_id)
    for row in LITE_COMMANDS:
        if row[2] and row[3]:
            owners.setdefault(row[2], set()).add(row[3])

    #: Keys the operating system or the edit control owns, which dictation uses
    #: without binding: they answer to nothing in either keymap by that name.
    ambient = {"Windows+H", "Enter"}

    page = _PAGE.read_text(encoding="utf-8")
    cells = re.findall(r'<td class="key">\s*<kbd>([^<]+)</kbd>', page)
    assert cells, 'no <td class="key"> chord cells found -- has the markup changed?'

    wrong = []
    for chord in dict.fromkeys(cells):
        if chord in ambient:
            continue
        commands = owners.get(chord)
        if not commands:
            wrong.append(f"{chord} is bound to nothing in either keymap")
        elif not any(
            "dictation" in c or c in {"edit.undo", "navigate.next_region", "cmd_undo"}
            for c in commands
        ):
            wrong.append(
                f"{chord} is presented as a dictation key but belongs to {sorted(commands)}"
            )
    assert not wrong, "dictation.html teaches a chord that is not dictation's:\n  " + "\n  ".join(
        wrong
    )
