"""Root test configuration.

Activates the ``_DEV_BUILD`` flag in :mod:`quill.core.paths` for the entire
test suite so that ``QUILL_DATA_DIR`` overrides (used by almost every test
fixture for isolation) are honoured.  Without this flag the guard added by
H-1-core silently ignores ``QUILL_DATA_DIR`` in non-dev builds, causing tests
to write to the real ``%APPDATA%\\Quill`` path and fail with stale state.
"""

from __future__ import annotations

import os
from collections.abc import Callable, Iterator
from pathlib import Path

import pytest


def pytest_configure(config: pytest.Config) -> None:
    """Force pytest's ``tmp_path`` base directory under ``$HOME``.

    ``paths.app_data_dir()`` only honours a ``QUILL_DATA_DIR`` override when
    it resolves under ``Path.home()`` (H-1-core: rejects an override that
    could redirect to an attacker-controlled path). Nearly every test that
    isolates ``QUILL_DATA_DIR`` does so via the ``tmp_path`` fixture -- but
    pytest's default tmp base is the OS temp directory, which on Windows
    happens to live under ``%USERPROFILE%`` (home-relative) but on macOS is
    ``/private/var/folders/...`` -- never under ``$HOME``. Every such test on
    macOS therefore silently failed the H-1-core check and fell through to
    the *real* ``~/.quill`` directory, reading and writing real state and
    cross-contaminating later tests. This was invisible until now because
    the macOS release CI job always segfaulted before pytest could report
    the resulting failures (see the voice_browser_dialog fix). Forcing
    basetemp under ``$HOME`` makes ``tmp_path`` satisfy the guard -- and
    thus provide real isolation -- on every platform, not just by accident
    on Windows.
    """
    if config.option.basetemp is None:
        config.option.basetemp = str(_session_basetemp())
    _redirect_comtypes_gen_dir()
    _configure_hypothesis()


def _redirect_comtypes_gen_dir() -> None:
    """Give comtypes a cache of its own, outside the developer's profile.

    comtypes writes a generated Python wrapper to disk the first time it
    touches a COM type library -- SAPI's SpVoice, oleacc, and the Rich Edit
    TOM that the rich-text surface needs. QUILL points that cache at
    ``running_app_data_dir() / "comtypes_gen"``, which is the right answer for
    the shipped app and the wrong one for a test run: it is inside the real
    profile, which the guard below refuses to let the suite write to.

    On a developer's machine that never showed, because the wrappers were
    already generated by running the app, so nothing was written and nothing
    was refused. On a fresh CI runner there is no cache, comtypes tries to
    generate, the guard fires, and the error surfaces as
    ``RichEditRtfError: Could not reach the Rich Edit text object model`` --
    which reads like the runner has no Rich Edit and is nothing of the kind.
    GATE-RICH-ROUNDTRIP's thirteen tests failed that way on every CI run while
    passing locally every time, which is the worst shape a red build can have:
    one that only the machine nobody watches can see.

    So the redirect happens here, before collection and therefore before
    anything can touch COM, and ``_redirected`` is set so the app's own
    redirect leaves it alone. The last path component stays ``comtypes_gen``
    because :mod:`tests.unit.platform.windows.test_comtypes_setup` checks the
    name. Per worker rather than shared: two xdist workers generating the same
    wrapper into the same folder is a race, and regenerating a handful of type
    libraries once per worker costs a second.
    """
    try:
        import comtypes.client as cc  # type: ignore[import-untyped]
    except Exception:  # noqa: BLE001 - not Windows, or no comtypes; nothing to do
        return
    worker = os.environ.get("PYTEST_XDIST_WORKER") or f"p{os.getpid()}"
    gen_dir = Path.home() / ".quill-pytest-tmp" / f"comtypes-{worker}" / "comtypes_gen"
    try:
        gen_dir.mkdir(parents=True, exist_ok=True)
    except OSError:
        return  # comtypes falls back to in-memory codegen on its own
    cc.gen_dir = str(gen_dir)
    try:
        from quill.platform.windows import comtypes_setup

        comtypes_setup._redirected = True
    except Exception:  # noqa: BLE001 - the app module is not importable here
        pass


def _session_basetemp() -> Path:
    """A temp root under ``$HOME`` that is unique to this pytest session.

    The directory has to live under ``$HOME`` (see above), but it must *not* be
    shared between concurrent sessions. pytest clears its basetemp at startup,
    so two runs at once -- a full suite in one terminal and a focused subset in
    another, or a background run alongside a foreground one -- had the second
    run deleting the first run's live temp files. That surfaced as hundreds of
    unrelated PermissionError/OSError setup failures in whichever session lost
    the race, which is about as misleading as a test failure can be.

    Keying on the process id gives each session its own root. xdist workers are
    unaffected: the controller passes them an explicit basetemp, so this hook
    never runs for them and they keep sharing the controller's tree.

    The root is created here because pytest is not going to: for an explicitly
    given basetemp it calls ``basetemp.mkdir(mode=0o700)`` with no ``parents``,
    which succeeded while this returned a path one level under ``$HOME`` and
    fails with ``FileNotFoundError`` now that it returns a per-session
    subdirectory. It only ever showed up on a machine where the root did not
    already exist -- i.e. every fresh CI runner, and never a developer's second
    run.
    """
    root = Path.home() / ".quill-pytest-tmp"
    root.mkdir(parents=True, exist_ok=True)
    token = os.environ.get("QUILL_PYTEST_RUN_ID") or f"run-{os.getpid()}"
    _prune_stale_runs(root)
    return root / token


#: The one group every machine-global test shares, and therefore the one
#: worker they all run on.
MACHINE_GLOBAL_GROUP = "machine-global"


@pytest.hookimpl(tryfirst=True)
def pytest_collection_modifyitems(config: pytest.Config, items: list[pytest.Item]) -> None:
    """Make ``-n auto --dist loadgroup`` safe: serialize what cannot be shared.

    The suite parallelizes cleanly except where a test drives a resource the
    *machine* owns rather than the process -- the Windows clipboard, the
    system-wide ``RegisterHotKey`` table, the screen-reader COM bridges. Two
    workers using one of those at the same time is not slow, it is wrong: the
    clipboard read belongs to whoever wrote last, and a hotkey can only be
    registered once on the whole desktop. In 2026-08 a worker died outright
    around the clipboard-backed clip-library dialog tests, taking its queued
    tests with it.

    Mechanics: with ``--dist loadgroup`` xdist schedules by ``xdist_group``
    mark. Tests marked ``machine_global`` all get the one shared
    ``machine-global`` group and therefore one worker; every other test gets its
    *file* as its group, preserving loadfile's file-affinity for module-scoped
    fixtures while fanning out. Serial runs are unaffected -- the marks are
    inert without xdist.

    The fast path is therefore:  ``pytest -q -n 8 --dist loadgroup``

    **The two ways this was wrong before, so neither is rediscovered.**

    *It was marked up and had no effect* (2026-08 to 2026-09-10). xdist reads
    the mark in **its own** ``pytest_collection_modifyitems``
    (``xdist/remote.py`` rewrites each item's nodeid to ``<nodeid>@<group>`` and
    the scheduler splits on that suffix), so this hook has to run first -- and
    without ``tryfirst`` it did not. Measured on a full ``-n 8`` run: all eight
    workers were running ``tests/unit/ui`` tests. The only visible symptom was
    ``test_clip_library_dialog.py::test_copy_defaults_to_plain_text_format``
    reading an empty clipboard under ``-n 8`` and passing on its own -- which
    reads as a flaky test rather than as the scheduler ignoring the group.

    *Then it was too coarse to terminate.* Adding ``tryfirst`` while the group
    was "everything under ``tests/unit/ui``" made the grouping real and put all
    **3,606** wx tests on one worker, and the suite then ran every test and
    never exited: 17,821 of 17,823 results, zero failures, no summary, eight
    processes still alive. Concentrating that many wx/COM objects in one worker
    hangs its shutdown, so the controller waits for a ``workerfinished`` that
    never comes.

    **The middle path, taken 2026-09-10.** Neither extreme: a directory is not
    the unit, a *resource* is. The mark is applied per file by hand
    (``pytestmark = pytest.mark.machine_global``) to the files that actually
    touch one -- which turned out to be far fewer than the directory suggested,
    because most of ``tests/unit/ui`` mocks ``wx.TheClipboard`` rather than using
    it. A new test that reaches for one of these resources has to say so, which
    is a line of code and a decision somebody made, rather than a directory it
    happened to be filed under.

    **What this fixed, and what it did not.** It fixed the hang it was aimed at:
    with a small group the ``tryfirst`` ordering is safe and the suite prints a
    summary, where the all-of-``tests/unit/ui`` version never did. Measured
    2026-09-10 over three full runs: one clean (**18,054 passed, 0 failed,
    4:41**), and two in which a worker died with ``node down: Not properly
    terminated`` -- once completing anyway with that worker's queued test
    reported failed, once leaving the controller waiting at 99%.

    Those crashes are **not** what this hook is about and predate it: a run
    before this change died the same way, with an extra
    ``INTERNALERROR ... KeyError: <WorkerController gw8>`` from xdist's own
    scheduler. They are a native crash somewhere in the wx/UI tests, they are
    unrelated to the clipboard grouping, and nobody has chased them.

    So: ``-n 8 --dist loadgroup`` is the **fast** path, not the authoritative
    one. A failure it reports is worth re-running on its own before believing
    it -- every one seen so far passed serially. The plain ``pytest -q`` run is
    the answer that counts (**18,117 passed, 0 failed, 14:15**, same tree, same
    day).
    """
    for item in items:
        if item.get_closest_marker("xdist_group") is not None:
            continue
        if item.get_closest_marker("machine_global") is not None:
            item.add_marker(pytest.mark.xdist_group(MACHINE_GLOBAL_GROUP))
            continue
        item.add_marker(pytest.mark.xdist_group(str(item.fspath).replace("\\", "/")))


def _prune_stale_runs(root: Path, *, max_age_seconds: float = 6 * 60 * 60) -> None:
    """Delete run directories left behind by long-finished sessions.

    Best-effort and deliberately conservative: only directories older than
    *max_age_seconds* are considered, so a session still running (whose files
    are being touched continuously) is never a candidate, and every error is
    swallowed -- failing to tidy up must never fail a test run.
    """
    import shutil
    import time

    try:
        entries = list(root.iterdir())
    except OSError:
        return
    cutoff = time.time() - max_age_seconds
    for entry in entries:
        # Everything under this root is pytest's, including the flat
        # ``test_<name>0`` directories left by the previous shared-basetemp
        # layout, so age is the only thing worth checking.
        try:
            if entry.stat().st_mtime >= cutoff:
                continue
            if entry.is_dir():
                shutil.rmtree(entry, ignore_errors=True)
            else:
                entry.unlink(missing_ok=True)
        except OSError:
            continue


def _configure_hypothesis() -> None:
    """Register the suite's Hypothesis profile (no-op if it isn't installed).

    ``deadline=None`` disables Hypothesis's per-example time limit. The default
    (200ms) measures wall-clock per generated example, which on a loaded CI
    runner -- four xdist workers plus AST-scanning gates -- turns an otherwise
    passing property into an intermittent DeadlineExceeded. Correctness, not
    latency, is what these properties assert; the suite-wide pytest ``timeout``
    still bounds a genuinely hung test.
    """
    try:
        from hypothesis import HealthCheck, settings
    except ModuleNotFoundError:  # property tests skip themselves without it
        return
    settings.register_profile(
        "quill",
        deadline=None,
        suppress_health_check=[HealthCheck.too_slow],
    )
    settings.load_profile("quill")


@pytest.fixture(autouse=True, scope="session")
def _enable_dev_build_for_tests() -> None:
    """Patch paths._DEV_BUILD=True for the whole test session."""
    import quill.core.paths as paths_mod

    paths_mod._DEV_BUILD = True


@pytest.fixture
def lite_recovery_store(tmp_path, monkeypatch):
    """QuillLite's recovery folder, redirected into *tmp_path*.

    ``quill.core.lite.recovery`` did ``from ... import recovery_dir``, so it
    holds its own reference and patching the paths module does nothing -- the
    exact failure ``_never_write_to_the_real_profile`` was written about. Two
    tests called ``new_slot`` without isolation and left a slot in the
    developer's live store on every run; those slots were part of the
    sixty-nine unsaved documents a user was offered in one Yes/No on launch.

    Any test that creates a real slot wants this.
    """
    store = tmp_path / "recovery-store"
    store.mkdir()
    monkeypatch.setattr("quill.core.lite.recovery.recovery_dir", lambda: store)
    return store


@pytest.fixture(autouse=True, scope="session")
def _never_write_to_the_real_profile() -> None:
    """Make the developer's own data directory read-only to the test suite.

    ``_DEV_BUILD`` plus ``QUILL_DATA_DIR`` isolates a test that remembers to
    ask for isolation. The failure mode is the test that *thinks* it did: patch
    ``quill.core.paths.app_data_dir`` and any module that did
    ``from quill.core.paths import app_data_dir`` still holds the original, so
    its writes land in the real profile with nothing to notice them.

    That is not hypothetical. A favorites test wrote its fixture stations --
    "Zeta", "Alpha", "Mu" -- straight into a developer's real
    ``radio_favorites.json``, replacing seven actual stations, and it went
    unnoticed for days because the suite passed every time.

    So the real directory is refused outright. Any write beneath it raises,
    naming the test that tried, which turns a silent data loss into a failure
    on the line that caused it.

    **Both profiles, since 2026-09-21.** The guard only ever covered QUILL's
    roaming profile, and QuillLite keeps its own under ``%LOCALAPPDATA%``. That
    gap had a cost with a number on it: ``quill.core.lite.recovery.new_slot``
    resolves the *real* recovery folder, and two tests in
    ``test_lite_save_path.py`` called it without isolation on every run, leaving
    a slot behind each time. Those slots were part of the sixty-nine unsaved
    documents a user was offered in one Yes/No on launch -- a test suite filling
    a developer's crash-recovery store, invisibly, for months.
    """
    import builtins
    import io
    import shutil
    import sys
    from pathlib import Path

    # The profile the *app* would use, computed the way app_data_dir computes
    # it -- deliberately not by calling app_data_dir(), which a test may have
    # already redirected.
    appdata = os.environ.get("APPDATA")
    if not appdata:
        yield
        return
    guarded = [(Path(appdata) / "Quill").resolve()]
    # QuillLite's own profile, which lives under LOCALAPPDATA rather than
    # APPDATA and was unguarded until 2026-09-21. Resolved the way
    # quill.core.lite.paths computes it, deliberately not by calling into that
    # module, which a test may already have redirected.
    local = os.environ.get("LOCALAPPDATA")
    if local:
        guarded.append((Path(local) / "QuillLite").resolve())
    original_open = builtins.open

    def _guarded_open(file, mode="r", *args, **kwargs):  # type: ignore[no-untyped-def]
        if any(flag in str(mode) for flag in ("w", "a", "x", "+")):
            try:
                target = Path(file).resolve()
            except (TypeError, ValueError, OSError):
                target = None
            if target is not None and any(target.is_relative_to(one) for one in guarded):
                raise AssertionError(
                    f"A test tried to write to a real profile: {target}. "
                    "Isolate it with the quill_data_dir fixture (or patch "
                    "app_data_dir / recovery_dir in *every* module that "
                    "imported the name), never the developer's own data."
                )
        return original_open(file, mode, *args, **kwargs)

    # Both names, and that is the second half of the 2026-09-21 fix.
    # ``builtins.open is io.open`` is the same object, but ``pathlib`` calls
    # ``io.open`` by attribute lookup on the module -- so patching only
    # ``builtins`` left every ``Path.write_text`` / ``write_bytes`` unguarded,
    # which is how ``write_json_atomic`` walked straight past this fixture.
    # Deleting is the other half, and it was never guarded at all. Writing is
    # what the fixture was written about, but a test that *removes* something
    # under a real profile loses data just as completely and leaves nothing
    # behind to notice -- there is no stray file afterwards to wonder about.
    #
    # It is guarded now because the recovery work of 2026-09-21 gave QUILL a
    # reason to delete: `begin_session` prunes autosave directories past the
    # keep window, so any test that builds a real MainFrame without isolating
    # its paths would take a month of a developer's crash-recovery snapshots
    # with it. That is a strictly worse failure than the one this fixture
    # already existed to prevent.
    original_rmtree = shutil.rmtree
    original_unlink = os.unlink
    original_remove = os.remove
    original_rmdir = os.rmdir
    original_path_unlink = Path.unlink

    def _refuse(target: object, verb: str) -> None:
        try:
            resolved = Path(target).resolve()  # type: ignore[arg-type]
        except (TypeError, ValueError, OSError):
            return
        if not any(resolved.is_relative_to(one) for one in guarded):
            return
        # Named on stderr *before* it is raised, because a refusal that is
        # caught tells nobody anything. Both leaks found on 2026-09-21 were
        # swallowed by a broad ``except Exception`` in the code under test --
        # the data was saved and the test still passed, so the guard protected
        # the profile and taught nothing about which test to fix. The line
        # below is the teaching half, and PYTEST_CURRENT_TEST is how it knows
        # whose fault it is.
        culprit = os.environ.get("PYTEST_CURRENT_TEST", "unknown test")
        message = (
            f"A test tried to {verb} a real profile: {resolved}. "
            "Isolate it with the quill_data_dir fixture (or patch "
            "app_data_dir / recovery_dir in *every* module that imported "
            "the name), never the developer's own data."
        )
        print(f"PROFILE GUARD: {culprit}: {message}", file=sys.stderr)
        raise AssertionError(message)

    def _guarded_rmtree(path, *args, **kwargs):  # type: ignore[no-untyped-def]
        _refuse(path, "delete a directory tree in")
        return original_rmtree(path, *args, **kwargs)

    def _guarded_unlink(path, *args, **kwargs):  # type: ignore[no-untyped-def]
        _refuse(path, "delete a file in")
        return original_unlink(path, *args, **kwargs)

    def _guarded_remove(path, *args, **kwargs):  # type: ignore[no-untyped-def]
        _refuse(path, "delete a file in")
        return original_remove(path, *args, **kwargs)

    def _guarded_rmdir(path, *args, **kwargs):  # type: ignore[no-untyped-def]
        _refuse(path, "remove a directory in")
        return original_rmdir(path, *args, **kwargs)

    def _guarded_path_unlink(self, *args, **kwargs):  # type: ignore[no-untyped-def]
        _refuse(self, "delete a file in")
        return original_path_unlink(self, *args, **kwargs)

    builtins.open = _guarded_open
    io.open = _guarded_open  # type: ignore[assignment]
    shutil.rmtree = _guarded_rmtree  # type: ignore[assignment]
    os.unlink = _guarded_unlink  # type: ignore[assignment]
    os.remove = _guarded_remove  # type: ignore[assignment]
    os.rmdir = _guarded_rmdir  # type: ignore[assignment]
    Path.unlink = _guarded_path_unlink  # type: ignore[assignment,method-assign]
    try:
        yield
    finally:
        builtins.open = original_open
        io.open = original_open  # type: ignore[assignment]
        shutil.rmtree = original_rmtree  # type: ignore[assignment]
        os.unlink = original_unlink  # type: ignore[assignment]
        os.remove = original_remove  # type: ignore[assignment]
        os.rmdir = original_rmdir  # type: ignore[assignment]
        Path.unlink = original_path_unlink  # type: ignore[assignment,method-assign]


#: Environment variables the leak guard ignores, and why. Everything else is a
#: leak and fails the test that caused it -- see :func:`_no_environment_leaks`.
#:
#: ``PYTEST_CURRENT_TEST`` is pytest's own bookkeeping and legitimately differs
#: between the setup and teardown phases the guard compares across.
#:
#: The other two are one-time *process* bootstrap performed by production code
#: rather than by a test. ``quill.core.spellcheck`` sets ``ENCHANT_CONFIG_DIR``
#: before the first Enchant broker is constructed -- the broker reads it at
#: construction, so it cannot be set afterwards -- and importing Enchant puts
#: its DLL directory on ``PATH``. Both are idempotent, both point inside the
#: isolated test profile, and undoing them would only make the next test that
#: spell-checks pay for the setup again.
_ENV_LEAK_ALLOWED = frozenset({"PYTEST_CURRENT_TEST", "ENCHANT_CONFIG_DIR", "PATH"})

#: Where the pre-test snapshot lives between the two hooks below.
_ENV_BEFORE: pytest.StashKey[dict[str, str]] = pytest.StashKey()


@pytest.hookimpl(hookwrapper=True)
def pytest_runtest_protocol(item: pytest.Item, nextitem: pytest.Item | None):
    """Snapshot ``os.environ`` before a test runs. Paired with the teardown hook."""
    item.stash[_ENV_BEFORE] = dict(os.environ)
    yield


@pytest.hookimpl(hookwrapper=True)
def pytest_runtest_teardown(item: pytest.Item, nextitem: pytest.Item | None):
    """Fail a test that changes ``os.environ`` and does not change it back.

    The footgun this exists for: ``monkeypatch.delenv(name, raising=False)``
    records **nothing** when the variable is already absent, so there is no
    entry to undo. If the code under test then writes that variable directly --
    which several QUILL functions do, deliberately -- the write outlives the
    test and every later test in the same process sees it.

    It went unnoticed for as long as the tests existed and surfaced on
    2026-09-11 as four failures in ``tests/unit/core/test_paths.py`` that had
    nothing to do with paths: a leaked ``QUILL_APP_ROOT`` made ``app_data_dir``
    resolve a portable root. It only appeared then because an unrelated new test
    file changed ``--dist=loadfile``'s file-to-worker split and put the guilty
    file and the victim file on one worker. That is the signature of the whole
    class -- it presents as "CI is flaky on a machine I cannot reproduce", which
    is why it needs a gate rather than vigilance.

    **A teardown hookwrapper, not an autouse fixture**, and that is not a style
    choice. A fixture finalizer cannot be made to run reliably last: the obvious
    arrangement (declare it first, so it is set up first and finalized last) was
    tried and does not hold -- ``monkeypatch`` undoes its work *after* such a
    fixture, so every ordinary ``monkeypatch.setenv`` was reported as a leak.
    The after-yield half of this hook runs once every finalizer for the item has
    completed, which is the only point where the question can be asked honestly.
    """
    yield
    before = item.stash.get(_ENV_BEFORE, None)
    if before is None:  # pragma: no cover - defensive; protocol hook always runs
        return
    after = dict(os.environ)
    names = set(before) ^ set(after)
    names |= {name for name in set(before) & set(after) if before[name] != after[name]}
    leaked = sorted(names - _ENV_LEAK_ALLOWED)
    if not leaked:
        return
    detail = ", ".join(
        f"{name}: {before.get(name, '<unset>')!r} -> {after.get(name, '<unset>')!r}"
        for name in leaked
    )
    # Put it back, so one leak does not cascade into every later test on this
    # worker and bury its own cause under a screenful of unrelated failures.
    for name in leaked:
        if name in before:
            os.environ[name] = before[name]
        else:
            os.environ.pop(name, None)
    raise AssertionError(
        f"this test changed os.environ and left it changed: {detail}. "
        "If the code under test writes the variable itself, note that "
        "monkeypatch.delenv(name, raising=False) records nothing when the name "
        "is already absent -- use the absent_env fixture, which guarantees "
        "removal on teardown. If the change is deliberate process bootstrap, "
        "add the name to _ENV_LEAK_ALLOWED in tests/conftest.py with the reason."
    )


@pytest.fixture
def absent_env(monkeypatch: pytest.MonkeyPatch) -> Iterator[Callable[..., None]]:
    """``absent_env("GH_TOKEN", ...)``: gone for the test, and gone afterwards.

    What ``monkeypatch.delenv(name, raising=False)`` looks like it does. The
    difference matters only when the code under test writes the variable itself,
    and that is exactly when it matters most -- see :func:`_no_environment_leaks`.
    """
    removed: list[str] = []

    def hide(*names: str) -> None:
        for name in names:
            monkeypatch.delenv(name, raising=False)
            removed.append(name)

    yield hide
    for name in removed:
        os.environ.pop(name, None)


@pytest.fixture(autouse=True)
def _no_ambient_provider_api_keys(monkeypatch: pytest.MonkeyPatch) -> None:
    """Hide the developer's own provider API keys from every test.

    ``assistant_ai.environment_api_key`` falls back to these variables, so a
    machine that legitimately exports one for unrelated work would otherwise
    make key-related tests pass (or fail) for reasons that have nothing to do
    with the code under test, and would differ from CI. Derived from the
    provider table so a newly supported variable cannot be forgotten here.
    """
    from quill.core.assistant_ai import _PROVIDER_ENV_VARS

    for names in _PROVIDER_ENV_VARS.values():
        for name in names:
            monkeypatch.delenv(name, raising=False)


@pytest.fixture(autouse=True)
def _reclaim_leaked_wx_windows():
    """Destroy wx top-level windows a test created but never destroyed.

    Windows caps a process at 10,000 User (window) handles. A wx.Frame or
    wx.Dialog that simply falls out of scope keeps its native window alive for
    the life of the process -- Python's garbage collector does not destroy a wx
    window, only ``Destroy()`` does. Measured: an App plus one Frame, one
    Dialog and twenty controls is 28 USER objects; dropping the frame without
    destroying it leaks 2, and at roughly 2-4 leaked per widget test the suite
    reaches the ceiling about three quarters of the way through. Past it every
    CreateWindowEx fails and the run collapses into failures that look
    unrelated to their own tests ("Failed to create dialog. Incorrect
    DLGTEMPLATE?", "can't append invalid menu to menubar").

    ``Destroy()`` only SCHEDULES deletion -- the handle is reclaimed when wx
    processes its pending-delete list -- so the event loop must be pumped
    afterwards or nothing is actually freed. (A first attempt at this fixture
    pumped with ``app.ProcessIdle()``, which does not exist on ``wx.App``; the
    AttributeError was swallowed by a broad except and the fixture silently did
    nothing, which is why it appeared not to help.)

    Only windows that appeared *during* the test are destroyed, so a module- or
    session-scoped fixture's window survives. Teardown never fails a test.
    """
    import sys

    def _live_wx():
        """The real wx module with a running App, else None.

        Some tests install a ``types.SimpleNamespace`` stub as ``sys.modules
        ["wx"]``, so the module being importable proves nothing -- check that
        the functions actually exist before calling them. Explicit rather than
        a broad try/except: swallowing AttributeError here is what hid the
        ``ProcessIdle`` mistake described above.
        """
        wx = sys.modules.get("wx")
        get_app = getattr(wx, "GetApp", None)
        if (
            wx is None
            or not callable(get_app)
            or not callable(getattr(wx, "GetTopLevelWindows", None))
        ):
            return None
        return wx if get_app() is not None else None

    def _top_level_ids() -> set[int]:
        wx = _live_wx()
        if wx is None:
            return set()
        return {id(win) for win in wx.GetTopLevelWindows()}

    before = _top_level_ids()
    yield
    wx = _live_wx()
    if wx is None:
        return
    leaked = [win for win in wx.GetTopLevelWindows() if id(win) not in before]
    if not leaked:
        return  # nothing to reclaim: skip the pump entirely (it is not free)
    for win in leaked:
        try:
            win.Destroy()
        except Exception:  # noqa: BLE001 - an already-dead window is fine
            pass
    try:
        wx.GetApp().ProcessPendingEvents()
        wx.SafeYield()
    except Exception:  # noqa: BLE001
        pass


@pytest.fixture()
def quill_data_dir(monkeypatch: pytest.MonkeyPatch, tmp_path: Path) -> Path:
    """Isolated QUILL_DATA_DIR guaranteed to be accepted by paths.app_data_dir().

    With _DEV_BUILD=True (set by the session fixture above), any resolvable
    path is accepted.  Use this fixture instead of a bare
    ``monkeypatch.setenv("QUILL_DATA_DIR", str(tmp_path))`` when the test
    needs a clean data directory — it wires up the env var and returns the
    path so test code can inspect written files.
    """
    monkeypatch.setenv("QUILL_DATA_DIR", str(tmp_path))
    return tmp_path


@pytest.fixture()
def isolated_profile(monkeypatch: pytest.MonkeyPatch, tmp_path: Path) -> Path:
    """Point the user-profile env vars at a per-test temp directory.

    Opt-in isolation for tests that read ``APPDATA``/``LOCALAPPDATA``/``HOME``/
    ``USERPROFILE`` (directly or via a fallback path) so they cannot pick up the
    developer's real profile state — the class of bug that made
    ``test_storage_mode_uses_portable_root`` pass in CI but fail locally.

    Deliberately **not** autouse: a blanket autouse breaks ~36 core tests that
    legitimately depend on the real profile environment (e.g. atomic-write and
    legacy-migration checks). Request this fixture explicitly in tests that touch
    profile-derived paths. Returns the fake home directory.
    """
    home = tmp_path / "_home"
    appdata = home / "AppData" / "Roaming"
    local = home / "AppData" / "Local"
    for path in (appdata, local):
        path.mkdir(parents=True, exist_ok=True)
    monkeypatch.setenv("APPDATA", str(appdata))
    monkeypatch.setenv("LOCALAPPDATA", str(local))
    monkeypatch.setenv("USERPROFILE", str(home))
    monkeypatch.setenv("HOME", str(home))
    return home
