"""ADP Assistant HTTP client: POST /api/ask (docs/API.md sections 2-6, 9).

One bearer credential per client app (label ``quill``), stored in the OS
credential vault -- never settings, never source. HTTPS over QUILL's
verified TLS context. Guardrail hits (rate limit, spend cap, missing model
key) arrive as a normal, friendly ``answer`` -- render them as answers, do
not retry; a real HTTP/connection failure raises :class:`AdpError` for the
caller to speak briefly and stop (never a silent hang). Voice deliberately
lives on the device (API.md section 7): this client never touches
``/api/speak`` or ``/api/transcribe``.

wx-free, strict-typed.
"""

from __future__ import annotations

import json
import urllib.error
import urllib.request

from quill.core.adp.models import AskResponse
from quill.core.error_codes import CodedError

#: Where the *user's* client key lives in the OS credential vault. A key here is
#: an explicit override (pasted/rotated in ADP Settings) and always wins over the
#: build-time bundled key below.
CREDENTIAL_TARGET = "quill.adp.client_key"

#: The hosted ADP backend (web app ``/``, ops dashboard ``/dashboard``, and the
#: ``/api/...`` surface this client uses). This is the direct FastAPI service
#: behind TLS -- not the WordPress site (bits-acb.org), which only fronts the
#: rollout/status gate. Overridable per-install via ADP Settings.
DEFAULT_BASE_URL = "https://adp.csedesigns.com"

#: The brain can run tools for a while; API.md recommends a generous read
#: timeout. Non-streaming ask stays comfortably under this in practice.
_TIMEOUT_SECONDS = 120.0

#: Hard cap on the response body we will buffer. A non-streaming answer is small
#: JSON; without a cap a hostile/misbehaving endpoint could stream unbounded
#: bytes into memory. 8 MiB is far above any legitimate ask response.
_MAX_RESPONSE_BYTES = 8 * 1024 * 1024


class AdpError(CodedError):
    """A real transport/HTTP failure talking to the ADP service (guardrail
    responses are NOT errors -- they arrive as normal answers)."""

    code = "QUILL-ADP-REQUEST-FAILED"


def _bundled_client_key() -> str:
    """The ``quill`` client key baked in at build time, or "" in an unbuilt
    checkout. Generated by ``tools/generate_adp_client_key.py`` into the
    gitignored ``quill._adp_client_key`` module -- one shared per-app key so a
    shipped build reaches the hosted service with no user setup (the ADP server
    authorizes on this key and derives the ``quill`` client label from it; the
    ``X-ADP-Client`` header is telemetry only). An extractable shipped key is a
    casual-abuse/rotation barrier, not real client auth -- matching the ADP
    team's own documented stance (docs/API.md section 2)."""
    try:
        from quill._adp_client_key import BUNDLED_ADP_CLIENT_KEY  # type: ignore[import-untyped]
    except ImportError:
        return ""
    return (BUNDLED_ADP_CLIENT_KEY or "").strip()


def stored_client_key() -> str:
    """The user's *override* key from the OS vault only ("" when unset).

    This is what ADP Settings shows and edits: an empty field means "use the
    built-in key," not "no key." Use :func:`load_client_key` for the value to
    actually send on a request (override first, then the bundled default)."""
    try:
        from quill.platform.windows.credential_manager import load_generic_credential

        stored = load_generic_credential(CREDENTIAL_TARGET)
        if stored is not None and stored.secret.strip():
            return stored.secret
    except Exception:  # noqa: BLE001 - non-Windows / no vault reads as unset
        return ""
    return ""


def load_client_key() -> str:
    """The ``quill`` client bearer key to send on a request.

    The user's vault override wins (so a paste in ADP Settings is always a
    rotation lever); otherwise the key baked into the build. "" when neither
    exists -- a dev checkout, or a server running with client-auth off."""
    return stored_client_key() or _bundled_client_key()


def save_client_key(key: str) -> bool:
    try:
        from quill.platform.windows.credential_manager import (
            delete_generic_credential,
            save_generic_credential,
        )

        if not key.strip():
            delete_generic_credential(CREDENTIAL_TARGET)
            return True
        save_generic_credential(CREDENTIAL_TARGET, key.strip(), user_name="quill")
        return True
    except Exception:  # noqa: BLE001
        return False


def ask(
    question: str,
    *,
    base_url: str = DEFAULT_BASE_URL,
    history: list[object] | None = None,
    user_name: str = "",
    safe_mode: bool = False,
    timeout: float = _TIMEOUT_SECONDS,
) -> AskResponse:
    """One non-streaming turn. ``history`` is the previous response's opaque
    ``history`` list (or None for a fresh conversation)."""
    if safe_mode:
        raise AdpError("The ADP Assistant is disabled in Safe Mode.")
    url = base_url.rstrip("/") + "/api/ask"
    if not url.startswith("https://"):
        raise AdpError("The ADP server address must use https.")
    payload: dict[str, object] = {"question": question.strip()}
    if history:
        payload["history"] = history
    if user_name.strip():
        payload["user_name"] = user_name.strip()
    headers = {
        "Content-Type": "application/json",
        "X-ADP-Client": "quill",
    }
    key = load_client_key()
    if key:
        # A key with a CR/LF (or other control char) would either raise a bare
        # ValueError deep in http.client (header injection guard) or, worse,
        # split the header. Reject it here as a clean AdpError instead.
        if any(ord(char) < 0x20 or ord(char) == 0x7F for char in key):
            raise AdpError("The stored ADP client key is malformed. Re-enter it in ADP Settings.")
        headers["Authorization"] = f"Bearer {key}"
    request = urllib.request.Request(  # noqa: S310 - https enforced above
        url, data=json.dumps(payload).encode("utf-8"), headers=headers, method="POST"
    )
    from quill.core.net import verified_ssl_context

    try:
        with urllib.request.urlopen(  # noqa: S310 - https + verified context
            request, timeout=timeout, context=verified_ssl_context()
        ) as response:
            raw = response.read(_MAX_RESPONSE_BYTES + 1)
            if len(raw) > _MAX_RESPONSE_BYTES:
                raise AdpError("The ADP service returned an unexpectedly large response.")
    except urllib.error.HTTPError as error:
        if error.code == 401:
            raise AdpError(
                "The ADP service rejected this app's access key. "
                "Check the client key in ADP Settings."
            ) from error
        raise AdpError(f"The ADP service returned an error ({error.code}).") from error
    except (urllib.error.URLError, OSError, TimeoutError) as error:
        raise AdpError(f"Could not reach the ADP service: {error}") from error
    try:
        data = json.loads(raw.decode("utf-8"))
    except ValueError as error:
        raise AdpError("The ADP service returned an unreadable response.") from error
    return AskResponse.from_dict(data)
