"""The Inno Setup ``[Registry]`` lines that register an app to open files.

One generator for every installer that registers a family app with Windows --
QUILL as a text editor (``installer/quill.iss``, through
``scripts/build_windows_distribution.py``) and Quill Radio as a media player
(``standalone/radio/installer/quill-radio.iss``) -- driven by the same
:class:`~quill.core.windows_editor.AppProfile` the in-app command writes for
one account. That is the whole point of it living in one place: an installer
and a command that build their keys from two lists will, one day, offer two
different sets of types.

Every line is always written (no task, component or check -- registering is
harmless because it never takes a default over) and every line is removed on
uninstall: a key that is the app's own goes with ``uninsdeletekey``; a value in
a key shared with every other app (a type's ``OpenWithProgids``,
``RegisteredApplications``) goes with ``uninsdeletevalue`` and leaves the key.
HKA is HKCU for a per-user install and HKLM for an administrator one.

wx-free, and it never touches a registry: it only writes text.
"""

from __future__ import annotations

from collections.abc import Sequence

from quill.core.windows_editor import AppProfile

__all__ = ["BEGIN_MARK", "END_MARK", "inno_command", "inno_registry_lines", "replace_block"]

#: Where a hand-written ``.iss`` keeps the generated block, so a test can
#: compare it with the generator and a script can rewrite it.
BEGIN_MARK = "; -- BEGIN generated by quill.core.windows_installer_lines --"
END_MARK = "; -- END generated by quill.core.windows_installer_lines --"


def inno_command(launcher: str, arguments: str = "") -> str:
    """An Inno-quoted ``"<launcher>" <arguments> "%1"`` (``""`` is one quote)."""
    middle = f" {arguments}" if arguments else ""
    return f'"""{launcher}""{middle} ""%1"""'


def inno_registry_lines(
    profile: AppProfile,
    *,
    launcher: str,
    launcher_arguments: str = "",
    application: str,
    icon: str,
    header: Sequence[str] = (),
) -> list[str]:
    """Every ``[Registry]`` line that registers *profile*'s app, in plan order.

    *launcher* is the program as Inno names it (``{app}\\QuillRadio.exe``),
    *launcher_arguments* what goes before the file (QUILL's ``-m quill``),
    *application* the ``Applications\\<name>`` key, and *icon* an Inno-quoted
    ``DefaultIcon`` value. *header* is the comment the block starts with.
    """
    classes = "Software\\Classes"
    progid = f"{classes}\\{profile.progid}"
    app_key = f"{classes}\\Applications\\{application}"
    capabilities = profile.capabilities_key
    command = inno_command(launcher, launcher_arguments)

    def value(subkey: str, name: str, data: str, flags: str = "uninsdeletekey") -> str:
        return (
            f'Root: HKA; Subkey: "{subkey}"; ValueType: string; ValueName: "{name}";'
            f" ValueData: {data}; Flags: {flags}"
        )

    lines = [
        *header,
        value(progid, "", f'"{profile.document_name}"'),
        value(progid, "FriendlyTypeName", f'"{profile.document_name}"'),
        value(f"{progid}\\DefaultIcon", "", icon),
        value(f"{progid}\\shell\\open\\command", "", command),
        value(app_key, "FriendlyAppName", f'"{profile.app_name}"'),
        value(f"{app_key}\\DefaultIcon", "", icon),
        value(f"{app_key}\\shell\\open\\command", "", command),
    ]
    lines += [value(f"{app_key}\\SupportedTypes", ext, '""') for ext in profile.extensions]
    lines += [
        "; One value in each type's own list, removed on uninstall; the type's key",
        "; is shared with every other app and is never deleted.",
    ]
    lines += [
        value(f"{classes}\\{ext}\\OpenWithProgids", profile.progid, '""', "uninsdeletevalue")
        for ext in profile.extensions
    ]
    owner = capabilities.rsplit("\\", 1)[0]
    lines += [
        f"; Capabilities + RegisteredApplications: what Default apps lists {profile.app_name} by.",
        f'Root: HKA; Subkey: "{owner}"; Flags: uninsdeletekeyifempty',
        value(capabilities, "ApplicationName", f'"{profile.app_name}"'),
        value(capabilities, "ApplicationDescription", f'"{profile.description}"'),
        value(capabilities, "ApplicationIcon", icon),
    ]
    lines += [
        value(f"{capabilities}\\FileAssociations", ext, f'"{profile.progid}"')
        for ext in profile.extensions
    ]
    lines.append(
        value(
            "Software\\RegisteredApplications",
            profile.app_name,
            f'"{capabilities}"',
            "uninsdeletevalue",
        )
    )
    if profile.verbs:
        lines += [
            "; Right-click verbs on every type, beside whatever app opens it; each verb's",
            "; key is this app's own, so uninstall removes the key.",
        ]
    for verb in profile.verbs:
        verb_command = inno_command(
            launcher, " ".join([launcher_arguments, *verb.arguments]).strip()
        )
        for ext in profile.extensions:
            base = f"{classes}\\SystemFileAssociations\\{ext}\\shell\\{verb.key}"
            lines.append(value(base, "", f'"{verb.label}"'))
            lines.append(value(f"{base}\\command", "", verb_command))
    return lines


def replace_block(text: str, lines: Sequence[str], *, newline: str = "\n") -> str:
    """*text* with everything between the two marks replaced by *lines*.

    Raises ``ValueError`` when the marks are missing, so a script never
    appends a second copy somewhere it was not meant to go.
    """
    start = text.find(BEGIN_MARK)
    end = text.find(END_MARK)
    if start < 0 or end < start:
        raise ValueError("The generated-block marks are missing")
    body = newline.join([BEGIN_MARK, *lines, ""])
    return text[:start] + body + text[end:]
