"""Generate Quill Converter's Explorer-verb registry block for Inno Setup.

The installer offers "Convert with Quill Converter" on the right-click menu of
every audio and video file the converter reads. Writing ~85 extensions by hand
into the .iss would drift from the format catalogue the first time somebody
added one, so the block is generated from :data:`quill.core.shell_verbs.
MEDIA_EXTENSIONS` (itself tested against ``quill.core.audio.formats``) and
``tests/unit/scripts/test_converter_installer.py`` fails when the committed file
is stale.

Per user (HKCU) and under ``SystemFileAssociations``, so the verb sits beside
whatever program already opens the file rather than taking its association.
The key name ``QuillConverter.Convert`` differs from QUILL's own
``Quill.convert`` on purpose: the two verbs can both be on without either
installer removing the other's on uninstall.

Usage::

    python scripts/build_converter_verb_iss.py          # write
    python scripts/build_converter_verb_iss.py --check  # exit 1 on drift
"""

from __future__ import annotations

import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO))

TARGET = REPO / "standalone" / "converter" / "installer" / "explorer-verb.isi"
KEY = "QuillConverter.Convert"
LABEL = "Convert with Quill Converter"


def render() -> str:
    from quill.core.shell_verbs import MEDIA_EXTENSIONS

    lines = [
        "; GENERATED by scripts/build_converter_verb_iss.py from",
        "; quill.core.shell_verbs.MEDIA_EXTENSIONS -- do not edit by hand.",
        "",
        "[Registry]",
    ]
    for ext in sorted(MEDIA_EXTENSIONS):
        base = rf"Software\Classes\SystemFileAssociations\{ext}\shell\{KEY}"
        common = "Check: WantsExplorerVerb"
        lines.append(
            f'Root: HKCU; Subkey: "{base}"; ValueType: string; ValueName: ""; '
            f'ValueData: "{LABEL}"; Flags: uninsdeletekey; {common}'
        )
        lines.append(
            f'Root: HKCU; Subkey: "{base}"; ValueType: string; ValueName: "Icon"; '
            f'ValueData: "{{app}}\\quill-converter.ico"; {common}'
        )
        lines.append(
            f'Root: HKCU; Subkey: "{base}"; ValueType: string; ValueName: "MultiSelectModel"; '
            f'ValueData: "Player"; {common}'
        )
        lines.append(
            f'Root: HKCU; Subkey: "{base}\\command"; ValueType: string; ValueName: ""; '
            f'ValueData: """{{app}}\\QuillConverter.exe"" ""%1"""; {common}'
        )
    return "\n".join(lines) + "\n"


def main(argv: list[str]) -> int:
    text = render()
    if "--check" in argv:
        current = TARGET.read_text(encoding="utf-8") if TARGET.is_file() else ""
        if current != text:
            print(f"{TARGET} is stale; run python scripts/build_converter_verb_iss.py")
            return 1
        print("explorer-verb.isi is current.")
        return 0
    TARGET.write_text(text, encoding="utf-8", newline="\n")
    print(f"Wrote {TARGET} ({text.count('[Registry]') and len(text.splitlines()) - 4} lines).")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
