"""Bake QUILL's YouTube OAuth client credential into a build. Generates no secret.

Same shape as ``generate_podcast_index_key.py`` and ``generate_adp_client_key.py``:
a Google Cloud OAuth 2.0 "Desktop app" client ID/secret pair, issued to a
registered developer outside this repository, is moved from the build
environment into a gitignored module the packager can see. Nothing here
invents or derives the pair.

**Why an app-wide client rather than one per listener.** Real-time YouTube
subscriptions/playlists (the "Connect YouTube Account" sign-in) need a
registered OAuth client somewhere. Asking every listener to create their own
Google Cloud project would repeat exactly the "seven steps of console work"
the Takeout CSV import (``youtube_takeout.py``) was built to avoid. So QUILL
carries its own, the same call the Podcast Index credential made.

**What this client is not.** A Desktop-app OAuth client secret is not
confidential the way a server-side secret is (Google's own docs say so; PKCE
is the real protection against a stolen authorization code) -- but the pair
still authorizes real per-user sign-in, so unlike the Podcast Index key this
is not a bare "identify the app" token. It is baked in exactly like every
other build-time credential here: never committed, and a rebuild with nothing
in the environment preserves whatever was baked before rather than wiping it.

**This alone does not make YouTube sign-in reachable.** The OAuth consent
screen for the ``youtube.readonly`` scope must also be verified by Google (or
the signed-in Google account added as a test user) before sign-in will work
for anyone; see the "Getting YouTube OAuth working" steps in
``docs/planning`` for the Cloud Console side of this.

Usage::

    QUILL_YOUTUBE_OAUTH_CLIENT_ID=<id> QUILL_YOUTUBE_OAUTH_CLIENT_SECRET=<secret> \\
        python tools/generate_youtube_oauth_client.py

Or, for a local build with nothing in the environment, point the two ``_FILE``
variables at files on disk holding the values.
"""

from __future__ import annotations

import os
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUTPUT_FILE = ROOT / "quill" / "_youtube_oauth_client.py"

CLIENT_ID_ENV = "QUILL_YOUTUBE_OAUTH_CLIENT_ID"
CLIENT_SECRET_ENV = "QUILL_YOUTUBE_OAUTH_CLIENT_SECRET"
#: Local-file fallbacks for a local build with nothing exported. Filesystem
#: only, never read from the network; below the env vars in precedence.
CLIENT_ID_FILE_ENV = "QUILL_YOUTUBE_OAUTH_CLIENT_ID_FILE"
CLIENT_SECRET_FILE_ENV = "QUILL_YOUTUBE_OAUTH_CLIENT_SECRET_FILE"


def write_module(client_id: str, client_secret: str, output_path: Path) -> None:
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(
        f"""# This file is generated by tools/generate_youtube_oauth_client.py. Do not edit by hand.
# Regenerate with:
#   QUILL_YOUTUBE_OAUTH_CLIENT_ID=<id> QUILL_YOUTUBE_OAUTH_CLIENT_SECRET=<secret> \\
#       python tools/generate_youtube_oauth_client.py

BUNDLED_YOUTUBE_OAUTH_CLIENT_ID = {client_id!r}
BUNDLED_YOUTUBE_OAUTH_CLIENT_SECRET = {client_secret!r}
""",
        encoding="utf-8",
    )


def read_existing(output_path: Path) -> tuple[str, str]:
    """The non-empty id and secret already written, or ``("", "")``.

    Lets a build with nothing in its environment preserve credentials set up
    earlier, so repeated dev/test builds stay consistent. Fresh values from
    the environment always win (:func:`resolve`).
    """
    if not output_path.is_file():
        return "", ""
    text = output_path.read_text("utf-8")

    def _find(name: str) -> str:
        match = re.search(rf"^{name} = (['\"])(.*)\1", text, re.MULTILINE)
        return match.group(2) if match else ""

    return (
        _find("BUNDLED_YOUTUBE_OAUTH_CLIENT_ID"),
        _find("BUNDLED_YOUTUBE_OAUTH_CLIENT_SECRET"),
    )


def _from_env(value_env: str, file_env: str) -> str:
    """One value: the env var, else the file it names. No network, ever."""
    value = os.environ.get(value_env, "").strip()
    if value:
        return value
    named = os.environ.get(file_env, "").strip()
    if named:
        try:
            return Path(named).read_text(encoding="utf-8").strip()
        except OSError:
            return ""
    return ""


def resolve() -> tuple[str, str]:
    """``(client_id, client_secret)`` from the environment or the files it names."""
    return (
        _from_env(CLIENT_ID_ENV, CLIENT_ID_FILE_ENV),
        _from_env(CLIENT_SECRET_ENV, CLIENT_SECRET_FILE_ENV),
    )


def main(argv: list[str] | None = None) -> int:
    client_id, client_secret = resolve()
    if not (client_id and client_secret):
        # Nothing from any source: keep working credentials already bundled
        # rather than wiping them, so a dev/test rebuild stays consistent.
        existing_id, existing_secret = read_existing(OUTPUT_FILE)
        if existing_id and existing_secret:
            print(
                "No YouTube OAuth client in env/file; preserving the existing "
                f"bundled pair in {OUTPUT_FILE}."
            )
            return 0
    write_module(client_id, client_secret, OUTPUT_FILE)
    if client_id and client_secret:
        print(f"Wrote {OUTPUT_FILE} with the bundled YouTube OAuth client.")
    else:
        # Half a credential is no credential: sign-in refuses without both,
        # so say plainly that the feature will report itself unavailable.
        print(
            f"No complete YouTube OAuth client pair found; wrote {OUTPUT_FILE} "
            "empty. Connect YouTube Account will report itself unavailable."
        )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
