"""Generate quill/_adp_client_key.py, the bundled ADP client bearer key.

Run before packaging (CI, local build). Reads ``QUILL_ADP_CLIENT_KEY`` from the
environment and writes it into a gitignored constant so a shipped QUILL build
reaches the hosted ADP service (``adp.csedesigns.com``) with no user setup. The
ADP server authorizes on this single per-app key and derives the ``quill``
client label from it; the ``X-ADP-Client`` header is telemetry only. An
extractable shipped key is a casual-abuse/rotation barrier, not real client
auth -- matching the ADP team's own documented stance (docs/API.md section 2).

This never fails: a missing env var just writes an empty key, so dev checkouts
and tests are unaffected. An empty bundled key degrades gracefully -- Ask ADP
then relies on server-side client-auth being off, or on a key the user pastes
into ADP Settings (which is stored in the OS credential vault and always wins
over this bundled default; see ``quill/core/adp/client.py``).

Usage::

    QUILL_ADP_CLIENT_KEY=<key> python tools/generate_adp_client_key.py
"""

from __future__ import annotations

import os
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUTPUT_FILE = ROOT / "quill" / "_adp_client_key.py"
ENV_VAR = "QUILL_ADP_CLIENT_KEY"
# Local-file fallback: points at a file on disk holding the key, for a local
# build with no QUILL_ADP_CLIENT_KEY in its environment. Filesystem-only, never
# read from the network; below the env var in precedence.
KEY_FILE_ENV = "QUILL_ADP_CLIENT_KEY_FILE"


def write_module(key: str, output_path: Path) -> None:
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(
        f"""# This file is generated by tools/generate_adp_client_key.py. Do not edit by hand.
# Regenerate with: QUILL_ADP_CLIENT_KEY=<key> python tools/generate_adp_client_key.py

BUNDLED_ADP_CLIENT_KEY = {key!r}
""",
        encoding="utf-8",
    )


def read_existing_key(output_path: Path) -> str:
    """Return the non-empty BUNDLED_ADP_CLIENT_KEY already written, or "".

    Lets a build with no ``QUILL_ADP_CLIENT_KEY`` in its environment preserve a
    working key set up earlier, so repeated dev/test builds stay consistent (you
    populate the key once and rebuilds preserve it). A fresh source key always
    wins via :func:`resolve_key`.
    """
    if not output_path.is_file():
        return ""
    text = output_path.read_text("utf-8")
    match = re.search(r"^BUNDLED_ADP_CLIENT_KEY = (['\"])(.*)\1", text, re.MULTILINE)
    return match.group(2) if match else ""


def resolve_key() -> str:
    """Find the ADP client key without any network access.

    Order: ``QUILL_ADP_CLIENT_KEY`` env var, then a file named by
    ``QUILL_ADP_CLIENT_KEY_FILE``. Returns "" when neither yields a key.
    """
    key = os.environ.get(ENV_VAR, "").strip()
    if key:
        return key
    file_env = os.environ.get(KEY_FILE_ENV, "").strip()
    if file_env:
        try:
            return Path(file_env).read_text(encoding="utf-8").strip()
        except OSError:
            return ""
    return ""


def main(argv: list[str] | None = None) -> int:
    key = resolve_key()
    if not key:
        # No key from any source: keep any working key already bundled rather
        # than wiping it to empty, so a dev/test rebuild stays consistent.
        existing = read_existing_key(OUTPUT_FILE)
        if existing:
            print(
                "No ADP client key in env/file; preserving the existing bundled key in "
                f"{OUTPUT_FILE}."
            )
            return 0
    write_module(key, OUTPUT_FILE)
    if key:
        print(f"Wrote {OUTPUT_FILE} with a bundled ADP client key.")
    else:
        print(
            f"No ADP client key found; wrote {OUTPUT_FILE} with an empty key "
            "(Ask ADP will rely on server-side client-auth being off, or a key "
            "pasted in ADP Settings)."
        )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
