"""Bake the Podcast Index credential into a build. It generates no secret.

The name follows the family (``generate_adp_client_key.py``, the feedback token,
the build-info and offline-edition markers) and does the same job they do:
**take a value that already exists outside the repository and write it into a
gitignored module the build then packages.** The key and secret are issued by
podcastindex.org to a registered developer -- they come from the vendor, not
from here, and nothing in this file invents or derives them.

Something has to do this. The credential must reach a shipped build, and it must
not be committed; those two facts together mean a build step that reads it from
the environment (or a file named by the environment) and writes it where the
packager can see it. That is all this is.

Run before packaging (CI, local build). Reads ``QUILL_PODCAST_INDEX_KEY`` and
``QUILL_PODCAST_INDEX_SECRET`` from the environment and writes them into a
gitignored module, so a shipped Quill Radio / QUILL Cast build reaches the
Podcast Index with no user setup at all.

**Why a bundled credential rather than one per listener.** The Podcast Index is
free and keyless-to-the-user by design: its keys identify the *application*, not
the person, and the project hands them out to anyone who signs up as a developer
in about a minute. Making every listener create a developer account before their
podcast search returns richer results would be the same mistake as asking them
to make a Google Cloud project to play a YouTube link -- seven steps of
developer console before anything happens. So the app carries its own.

**What that credential is, and is not.** An extractable shipped key is a
casual-abuse and rotation barrier, not authentication -- exactly the stance the
existing ADP client key documents (``tools/generate_adp_client_key.py``). It
identifies the app to a directory that serves public data; it authorises nothing
on the listener's behalf, reads no account, and carries no personal data. If it
is ever abused it is rotated in one build, and a listener who wants their own
can paste one in (the vault override in
``quill/core/podcasts/podcast_index.py`` always wins).

This never fails: missing values just write empty strings, so dev checkouts and
tests are unaffected, and the feature degrades to "unavailable" out loud rather
than breaking anything that already worked.

Usage::

    QUILL_PODCAST_INDEX_KEY=<key> QUILL_PODCAST_INDEX_SECRET=<secret> \\
        python tools/generate_podcast_index_key.py

Or, for a local build with nothing in the environment, point the two ``_FILE``
variables at files on disk holding the values.
"""

from __future__ import annotations

import os
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUTPUT_FILE = ROOT / "quill" / "_podcast_index_key.py"

KEY_ENV = "QUILL_PODCAST_INDEX_KEY"
SECRET_ENV = "QUILL_PODCAST_INDEX_SECRET"
#: Local-file fallbacks: each points at a file on disk holding the value, for a
#: local build with nothing in its environment. Filesystem-only, never read from
#: the network; below the env vars in precedence.
KEY_FILE_ENV = "QUILL_PODCAST_INDEX_KEY_FILE"
SECRET_FILE_ENV = "QUILL_PODCAST_INDEX_SECRET_FILE"


def write_module(key: str, secret: str, output_path: Path) -> None:
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(
        f"""# This file is generated by tools/generate_podcast_index_key.py. Do not edit by hand.
# Regenerate with:
#   QUILL_PODCAST_INDEX_KEY=<key> QUILL_PODCAST_INDEX_SECRET=<secret> \\
#       python tools/generate_podcast_index_key.py

BUNDLED_PODCAST_INDEX_KEY = {key!r}
BUNDLED_PODCAST_INDEX_SECRET = {secret!r}
""",
        encoding="utf-8",
    )


def read_existing(output_path: Path) -> tuple[str, str]:
    """The non-empty key and secret already written, or ``("", "")``.

    Lets a build with nothing in its environment preserve credentials set up
    earlier, so repeated dev/test builds stay consistent. Fresh values from the
    environment always win (:func:`resolve`).
    """
    if not output_path.is_file():
        return "", ""
    text = output_path.read_text("utf-8")

    def _find(name: str) -> str:
        match = re.search(rf"^{name} = (['\"])(.*)\1", text, re.MULTILINE)
        return match.group(2) if match else ""

    return _find("BUNDLED_PODCAST_INDEX_KEY"), _find("BUNDLED_PODCAST_INDEX_SECRET")


def _from_env(value_env: str, file_env: str) -> str:
    """One value: the env var, else the file it names. No network, ever."""
    value = os.environ.get(value_env, "").strip()
    if value:
        return value
    named = os.environ.get(file_env, "").strip()
    if named:
        try:
            return Path(named).read_text(encoding="utf-8").strip()
        except OSError:
            return ""
    return ""


def resolve() -> tuple[str, str]:
    """``(key, secret)`` from the environment or the files it names."""
    return _from_env(KEY_ENV, KEY_FILE_ENV), _from_env(SECRET_ENV, SECRET_FILE_ENV)


def main(argv: list[str] | None = None) -> int:
    key, secret = resolve()
    if not (key and secret):
        # Nothing from any source: keep working credentials already bundled
        # rather than wiping them, so a dev/test rebuild stays consistent.
        existing_key, existing_secret = read_existing(OUTPUT_FILE)
        if existing_key and existing_secret:
            print(
                "No Podcast Index credentials in env/file; preserving the existing "
                f"bundled pair in {OUTPUT_FILE}."
            )
            return 0
    write_module(key, secret, OUTPUT_FILE)
    if key and secret:
        print(f"Wrote {OUTPUT_FILE} with bundled Podcast Index credentials.")
    else:
        # Half a credential is no credential: the client refuses to sign a
        # request without both, so say plainly that the feature will be off.
        print(
            f"No complete Podcast Index credential pair found; wrote {OUTPUT_FILE} "
            "empty. Podcast Index features will report themselves unavailable."
        )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
